language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

env:
  - REPORT_EXIT_STATUS=1 TESTS="-q --show-diff" TEST_PHP_EXECUTABLE=php

before_script:
  - sh travis/install_nacl.sh
  - arch=`nacl-20110221/build/travis/bin/okabi`
  - phpize
  - ./configure --with-nacl=nacl-20110221/build/travis/include/$arch --with-nacl-libdir=nacl-20110221/build/travis/lib/$arch
  - make

script: make test

notifications:
  email:
    - gasol.wu+travis@gmail.com
